-- IDB, NameA
Insert into BA values (91, "Аарон Аппельфельд");
Insert into BA values (92, "Абрахам Дэниел");
Insert into BA values (93, "Абсолют Павел");
Insert into BA values (94, "Абсолют Павел");
Insert into BA values (95, "Абсолют Павел");
Insert into BA values (96, "Абсолют Павел");
Insert into BA values (97, "Аверин Н.В.");
Insert into BA values (97, "Вардунас И.В.");
Insert into BA values (98, "Аверин Никита Владимирович");
Insert into BA values (99, "Аволедо Туллио");
Insert into BA values (100, "Адам Нэвилл");
Insert into BA values (101, "Адам Робертс");
Insert into BA values (102, "Адамов Григорий Борисович");
Insert into BA values (103, "Адамс Дуглас");
Insert into BA values (104, "Адамс Дуглас");
Insert into BA values (105, "Адамс Дуглас");
Insert into BA values (106, "Адамс Дуглас");
Insert into BA values (107, "Адамс Дуглас");
Insert into BA values (108, "Адамс Дуглас");
Insert into BA values (109, "Аксенов Даниил");
Insert into BA values (110, "Акулова Мария");
Insert into BA values (111, "Акунин Борис");
Insert into BA values (112, "Акунин Борис");
Insert into BA values (113, "Акунин Борис");
Insert into BA values (114, "Акунин Борис");
Insert into BA values (115, "Акунин Борис");
Insert into BA values (116, "Акунин Борис");
Insert into BA values (117, "Акунин Борис");
Insert into BA values (118, "Акунин Борис");
Insert into BA values (119, "Акунин Борис");
Insert into BA values (120, "Акунин Борис");
Insert into BA values (121, "Акунин Борис");
Insert into BA values (122, "Акунин Борис");
Insert into BA values (123, "Акунин Борис");
Insert into BA values (124, "Акунин Борис");
Insert into BA values (125, "Акунин Борис");
Insert into BA values (126, "Акунин Борис");
Insert into BA values (127, "Акунин Борис");
Insert into BA values (128, "Акунин Борис");
Insert into BA values (129, "Акунин Борис");
Insert into BA values (130, "Акунин Борис");
Insert into BA values (131, "Акунин Борис");
Insert into BA values (132, "Акунин Борис");
Insert into BA values (133, "Алан Дин Фостер");
Insert into BA values (134, "Алан Дин Фостер");
Insert into BA values (135, "Алекс де Клемешье");
Insert into BA values (136, "Алекс Лэмб");
Insert into BA values (137, "Александер Джен");
Insert into BA values (138, "Александр Абрамов");
Insert into BA values (139, "Александр Дюма");
Insert into BA values (140, "Александр Мазин");
Insert into BA values (141, "Александр Прозоров");
Insert into BA values (141, "Алексей Живой");
Insert into BA values (142, "Александр Прокопович");
Insert into BA values (143, "Александр Ратнер");
Insert into BA values (144, "Александра Бракен");
Insert into BA values (145, "Александра Бракен");
Insert into BA values (146, "Александров Николай Дмитриевич");
Insert into BA values (147, "Алексей Лукьянов");
Insert into BA values (148, "Алигьери Данте");
Insert into BA values (149, "Алина Борисова");
Insert into BA values (150, "Алиса Дорн");
Insert into BA values (151, "Алиса Куитни");
Insert into BA values (152, "Алисия Хименес Бартлетт");
Insert into BA values (153, "Алла Хемлин");
Insert into BA values (154, "Аллингем Марджери");
Insert into BA values (155, "Алтамиров Шамиль Рамазанович");
Insert into BA values (156, "Анастасия Андрианова");
Insert into BA values (157, "Анджей Сапковский");
Insert into BA values (158, "Анджей Сапковский");
Insert into BA values (159, "Анджей Сапковский");
Insert into BA values (160, "Анджей Сапковский");
Insert into BA values (161, "Анджей Сапковский");
Insert into BA values (162, "Анджей Сапковский");
Insert into BA values (163, "Анна Коэн");
Insert into BA values (164, "Анна Невер");
Insert into BA values (165, "Анна Невер");
Insert into BA values (166, "Анна Нельсон");
Insert into BA values (169, "Антонов Сергей Валентинович");
Insert into BA values (170, "Антонов Сергей Валентинович");
Insert into BA values (171, "Антонов Сергей Валентинович");
Insert into BA values (172, "Аньес Мартен-Люган");
Insert into BA values (173, "Аньес Мартен-Люган");
Insert into BA values (174, "Аньес Мартен-Люган");
Insert into BA values (175, "Аркадий Стругацкий");
Insert into BA values (175, "Борис Стругацкий");
Insert into BA values (176, "Аркадий Стругацкий");
Insert into BA values (176, "Борис Стругацкий");
Insert into BA values (177, "Арментроут Дженнифер");
Insert into BA values (178, "Армстронг Шарлотт");
Insert into BA values (179, "Арнальд Индридасон");
Insert into BA values (180, "Артур Конан Дойл");
Insert into BA values (181, "Асачёв Тарас Сергеевич");
Insert into BA values (182, "Асприн Роберт");
Insert into BA values (183, "Астафьев Виктор Петрович");
Insert into BA values (184, "Астафьев Виктор Петрович");
Insert into BA values (185, "Астрадени Джейн");
Insert into BA values (186, "Афанасьев Роман Сергеевич");
Insert into BA values (187, "Ахматова Анна Андреевна");
Insert into BA values (188, "Бакулина Е.С.");
Insert into BA values (189, "Балашов Дмитрий Михайлович");
Insert into BA values (190, "Баркли Линвуд");
Insert into BA values (191, "Басинский П.В.");
Insert into BA values (192, "Басинский Павел Валерьевич");
Insert into BA values (193, "Басинский Павел Валерьевич");
Insert into BA values (194, "Батракова Наталья Николаевна");
Insert into BA values (195, "Батракова Наталья Николаевна");
Insert into BA values (196, "Батракова Наталья Николаевна");
Insert into BA values (197, "Баунт Сергей");
Insert into BA values (198, "Бауров Александр Юрьевич");
Insert into BA values (199, "Бауров Александр Юрьевич");
Insert into BA values (200, "Бахман Ричард (Кинг Стивен)");
Insert into BA values (201, "Бачигалупи Паоло");
Insert into BA values (202, "Белинг Стив");
Insert into BA values (203, "Бёлль Генрих");
Insert into BA values (204, "Белый Александр");
Insert into BA values (205, "Беляев Александр Романович");
Insert into BA values (206, "Беляев Александр Романович");
Insert into BA values (207, "Беляев Александр Романович");
Insert into BA values (208, "Бенгт Янгфельдт");
Insert into BA values (209, "Бёрджесс Энтони");
Insert into BA values (210, "Бёрджесс Энтони");
Insert into BA values (211, "Билл Смит");
Insert into BA values (212, "Билл Смит");
Insert into BA values (213, "Блейк Николас");
Insert into BA values (214, "Блэкмен Хейден");
Insert into BA values (215, "Блэр Тиндалл");
Insert into BA values (216, "Богданович Л.А.");
Insert into BA values (217, "Богомолов Станислав");
Insert into BA values (218, "Боккаччо Джованни");
Insert into BA values (219, "Борис Акунин");
Insert into BA values (220, "Борисов Алексей Николаевич");
Insert into BA values (221, "Борисов Алексей Николаевич");
Insert into BA values (222, "Борисов Олег Николаевич");
Insert into BA values (223, "Борисова Анна");
Insert into BA values (224, "Боталова Мария");
Insert into BA values (225, "Брайан Томас Шмидт");
Insert into BA values (226, "Браннер Джон");
Insert into BA values (227, "Браун Дэн");
Insert into BA values (228, "Браун Дэн");
Insert into BA values (229, "Браун Дэн");
Insert into BA values (230, "Браун Дэн");
Insert into BA values (231, "Браун Дэн");
Insert into BA values (232, "Браун Дэн");
Insert into BA values (233, "Браун Дэн");
Insert into BA values (234, "Браун Дэн");
Insert into BA values (235, "Браун Дэн");
Insert into BA values (236, "Браун Дэн");
Insert into BA values (237, "Браун Дэн");
Insert into BA values (238, "Браун Дэн");
Insert into BA values (239, "Браун Дэн");
Insert into BA values (240, "Браун Дэн");
Insert into BA values (241, "Браун Дэн");
Insert into BA values (242, "Британ Мария");
Insert into BA values (243, "Бронте Шарлотта");
Insert into BA values (244, "Бронте Шарлотта");
Insert into BA values (245, "Броуди Фрэнсис");
Insert into BA values (246, "Брусникин Анатолий");
Insert into BA values (247, "Брэм Стокер");
Insert into BA values (248, "Брэндон Снайдер");
Insert into BA values (249, "Брюс Лео");
Insert into BA values (250, "Буджолд Лоис Макмастер");
Insert into BA values (251, "Букшпан Дэниел");
Insert into BA values (252, "Булгаков Михаил Афанасьевич");
Insert into BA values (253, "Булгаков Михаил Афанасьевич");
Insert into BA values (254, "Булгаков Михаил Афанасьевич");
Insert into BA values (255, "Булгаков Михаил Афанасьевич");
Insert into BA values (256, "Буторин Андрей Русланович");
Insert into BA values (257, "Буторин Андрей Русланович");
Insert into BA values (258, "Буццати Дино");
Insert into BA values (259, "Буянов Андрей Игоревич");
Insert into BA values (260, "Быченин Александр Павлович");
Insert into BA values (261, "Бэгшоу Тилли");
Insert into BA values (262, "Бэгшоу Тилли");
Insert into BA values (263, "Бэгшоу Тилли");
Insert into BA values (264, "Бэгшоу Тилли");
Insert into BA values (265, "Вайсбергер Лорен");
Insert into BA values (266, "Вайсбергер Лорен");
Insert into BA values (267, "Валерий Шубинский");
Insert into BA values (268, "Валиуллин");
Insert into BA values (269, "Валишевский Казимир");
Insert into BA values (270, "Валишевский Казимир");
Insert into BA values (271, "Валишевский Казимир");
Insert into BA values (272, "Валишевский Казимир");
Insert into BA values (273, "Варвара Еналь");
Insert into BA values (274, "Вардунас Игорь Владимирович");
Insert into BA values (275, "Василий Ян");
Insert into BA values (276, "Васильев Борис Львович");
Insert into BA values (277, "Васильев Владимир");
Insert into BA values (278, "Васильев Владимир");
Insert into BA values (279, "Вебер В.А.");
Insert into BA values (280, "Вегнер Роберт М.");
Insert into BA values (281, "Вегнер Роберт М.");
Insert into BA values (282, "Вегнер Роберт М.");
Insert into BA values (283, "Велихов Е.П.");
Insert into BA values (284, "Веллер Михаил");
Insert into BA values (285, "Веллер Михаил Иосифович");
Insert into BA values (286, "Веллер Михаил Иосифович");
Insert into BA values (287, "Веллер Михаил Иосифович");
Insert into BA values (288, "Веллер Михаил Иосифович");
Insert into BA values (289, "Веллер Михаил Иосифович");
Insert into BA values (290, "Веллер Михаил Иосифович");
Insert into BA values (291, "Вересаев Викентий Викентьевич");
Insert into BA values (292, "Верхова Екатерина");
Insert into BA values (293, "Ви Карвин");
Insert into BA values (294, "Вика Кисимяка");
Insert into BA values (295, "Викерс Рой");
Insert into BA values (296, "Виктория Войцек");
Insert into BA values (297, "Виктория Токарева");
Insert into BA values (298, "Виктория Токарева");
Insert into BA values (299, "Виктория Токарева");
Insert into BA values (300, "Виктория Шваб");
Insert into BA values (301, "Вильмонт Екатерина");
Insert into BA values (302, "Вингет Олли");
Insert into BA values (303, "Витухновская А.А.");
Insert into BA values (304, "Влад Савин");
Insert into BA values (305, "Владимир Орлов");
Insert into BA values (306, "Во Ивлин");
Insert into BA values (307, "Водолазкин Евгений Германович");
Insert into BA values (308, "Волнистая Наталия Николаевна");
Insert into BA values (309, "Волос Андрей Германович");
Insert into BA values (310, "Волошина Полина");
Insert into BA values (311, "Вольф В.Е.");
Insert into BA values (312, "Воннегут Курт");
Insert into BA values (313, "Воннегут Курт");
Insert into BA values (314, "Воннегут Курт");
Insert into BA values (315, "Воннегут Курт");
Insert into BA values (316, "Воннегут Курт");
Insert into BA values (317, "Воннегут Курт");
Insert into BA values (318, "Вудхаус Пелам Гренвилл");
Insert into BA values (319, "Вудхаус Пелам Гренвилл");
Insert into BA values (320, "Вулф Вирджиния");
Insert into BA values (321, "Вульф П.Л.");
Insert into BA values (322, "Выборнов Наиль Эдуардович");
Insert into BA values (323, "Выставной Владислав Валериевич");
Insert into BA values (324, "Выставной Владислав Валериевич");
Insert into BA values (325, "Габриэль Гарсиа Маркес");
Insert into BA values (326, "Гавальда Анна");
Insert into BA values (327, "Гавальда Анна");
Insert into BA values (328, "Гавальда Анна");
Insert into BA values (329, "Гавальда Анна");
Insert into BA values (330, "Гамильтон Лорел");
Insert into BA values (331, "Ганиева А.А.");
Insert into BA values (332, "Гарди Томас");
Insert into BA values (333, "Гарри Стайлс");
Insert into BA values (334, "Гарсиа Маркес Габриэль");
Insert into BA values (335, "Гарсиа Маркес Габриэль");
Insert into BA values (336, "Гарсиа Маркес Габриэль");
Insert into BA values (337, "Гарсиа Маркес Габриэль");
Insert into BA values (338, "Гарсиа Маркес Габриэль");
Insert into BA values (339, "Гарсиа Маркес Габриэль");
Insert into BA values (340, "Гарсиа Маркес Габриэль");
Insert into BA values (341, "Гарсиа Маркес Габриэль");
Insert into BA values (342, "Гарсиа Маркес Габриэль");
Insert into BA values (343, "Гаскелл Элизабет");
Insert into BA values (344, "Гашек Ярослав");
Insert into BA values (345, "Гашек Ярослав");
Insert into BA values (346, "Гаэль Фай");
Insert into BA values (347, "Гейман Нил");
Insert into BA values (348, "Гейман Нил");
Insert into BA values (349, "Генис А.А.");
Insert into BA values (350, "Андерсон Кевин");
Insert into BA values (350, "Герберт Брайан");
Insert into BA values (351, "Андерсон Кевин");
Insert into BA values (351, "Герберт Брайан");
Insert into BA values (352, "Андерсон Кевин");
Insert into BA values (352, "Герберт Брайан");
Insert into BA values (353, "Андерсон Кевин");
Insert into BA values (353, "Герберт Брайан");
Insert into BA values (354, "Андерсон Кевин");
Insert into BA values (354, "Герберт Брайан");
Insert into BA values (355, "Герберт Фрэнк");
Insert into BA values (356, "Герберт Фрэнк");
Insert into BA values (357, "Герберт Фрэнк");
Insert into BA values (358, "Гессе Герман");
Insert into BA values (359, "Гессе Герман");
Insert into BA values (360, "Гессе Герман");
Insert into BA values (361, "Гессе Герман");
Insert into BA values (362, "Гессе Герман");
Insert into BA values (363, "Гете Иоганн Вольфганг");
Insert into BA values (364, "Гете Иоганн Вольфганг");
Insert into BA values (365, "Гиляровский В.А.");
Insert into BA values (366, "Гиляровский В.А.");
Insert into BA values (367, "Гиляровский В.А.");
Insert into BA values (368, "Гинзбург Евгения Соломоновна");
Insert into BA values (369, "Гинзбург Евгения Соломоновна");
Insert into BA values (370, "Глуховский Дмитрий Алексеевич");
Insert into BA values (371, "Глуховский Дмитрий Алексеевич");
Insert into BA values (372, "Глуховский Дмитрий Алексеевич");
Insert into BA values (373, "Гнатюк В.С.");
Insert into BA values (373, "Гнатюк Ю.В.");
Insert into BA values (374, "Говард Лавкрафт");
Insert into BA values (375, "Гоголь Николай Васильевич");
Insert into BA values (376, "Гоголь Николай Васильевич");
Insert into BA values (377, "Гоголь Николай Васильевич");
Insert into BA values (378, "Гоголь Николай Васильевич");
Insert into BA values (379, "Голден Артур");
Insert into BA values (380, "Голден Артур");
Insert into BA values (381, "Голден Кристи");
Insert into BA values (382, "Голдинг Уильям");
Insert into BA values (383, "Голдинг Уильям");
Insert into BA values (384, "Голдинг Уильям");
Insert into BA values (385, "Голдинг Уильям");
Insert into BA values (386, "Головачёв Василий Васильевич");
Insert into BA values (387, "Голомшток Игорь Наумович");
Insert into BA values (388, "Голотвина Ольга");
Insert into BA values (389, "Голсуорси Джон");
Insert into BA values (390, "Голсуорси Джон");
Insert into BA values (391, "Голсуорси Джон");
Insert into BA values (392, "Гомер");
Insert into BA values (393, "Гончаров Иван Александрович");
Insert into BA values (394, "Гончаров Иван Александрович");
Insert into BA values (395, "Гончаров Иван Александрович");
Insert into BA values (396, "Горбачев М.С.");
Insert into BA values (397, "Горелик Елена");
Insert into BA values (398, "Горький Максим");
Insert into BA values (399, "Гранин Даниил Александрович");
Insert into BA values (400, "Гребенщиков Андрей Анатольевич");
Insert into BA values (401, "Бакулин Вячеслав Александрович");
Insert into BA values (401, "Гребенщиков Андрей Анатольевич");
Insert into BA values (402, "Грег Киз");
Insert into BA values (403, "Грег Кокс");
Insert into BA values (404, "Грейди Джеймс");
Insert into BA values (405, "Грин Грэм");
Insert into BA values (406, "Гришэм Джон");
Insert into BA values (407, "Гришэм Джон");
Insert into BA values (408, "Гришэм Джон");
Insert into BA values (409, "Гришэм Джон");
Insert into BA values (410, "Гришэм Джон");
Insert into BA values (411, "Гришэм Джон");
Insert into BA values (412, "Гришэм Джон");
Insert into BA values (413, "Гришэм Джон");
Insert into BA values (414, "Гришэм Джон");
Insert into BA values (415, "Гришэм Джон");
Insert into BA values (416, "Гудкайнд Терри");
Insert into BA values (417, "Гудкайнд Терри");
Insert into BA values (418, "Гудкайнд Терри");
Insert into BA values (419, "Гудкайнд Терри");
Insert into BA values (420, "Гумилев Л.Н.");
Insert into BA values (421, "Гумилев Лев Николаевич");
Insert into BA values (422, "Гусейнова Ольга");
Insert into BA values (423, "Гюго Виктор");
Insert into BA values (424, "Гюго Виктор");
Insert into BA values (425, "Гюго Виктор");
Insert into BA values (426, "Гюго Виктор");
Insert into BA values (427, "Д Хоффман");
Insert into BA values (428, "Д. Уильямс");
Insert into BA values (429, "Давид Фонкинос");
Insert into BA values (430, "Дай Андрей");
Insert into BA values (431, "Даль Дмитрий");
Insert into BA values (432, "Данилова С.Д.");
Insert into BA values (433, "Данильченко Олег Викторович");
Insert into BA values (434, "Данильченко Олег Викторович");
Insert into BA values (435, "Данте Алигьери");
Insert into BA values (436, "Дарвин Чарлз Роберт");
Insert into BA values (437, "Даррелл Лоренс");
Insert into BA values (438, "Дарси Белл");
Insert into BA values (439, "Дашкова Полина Викторовна");
Insert into BA values (440, "Дашкова Полина.");
Insert into BA values (441, "де Клемешье Алекс");
Insert into BA values (442, "Деверо Джуд");
Insert into BA values (443, "Девин Грейсон");
Insert into BA values (444, "Дейтон Лен");
Insert into BA values (445, "Демидова Элона Вячеславовна");
Insert into BA values (445, "Шкиль Евгений Юрьевич");
Insert into BA values (446, "Демченко Антон");
Insert into BA values (447, "Демченко Антон Витальевич");
Insert into BA values (448, "Демченко Антон Витальевич");
Insert into BA values (449, "Деннард Сьюзан");
Insert into BA values (450, "Джанет Эдвардс");
Insert into BA values (451, "Джевинс Мари");
Insert into BA values (452, "Джей Эшер");
Insert into BA values (453, "Джей Эшер");
Insert into BA values (454, "Джеймс А. Мур");
Insert into BA values (455, "Джеймс Миранда");
Insert into BA values (456, "Джеймс Филлис Дороти");
Insert into BA values (457, "Джейн А.");
Insert into BA values (458, "Джейн Остен");
Insert into BA values (459, "Джейсон Старр");
Insert into BA values (460, "Дженни Хан");
Insert into BA values (461, "Дженни Хан");
Insert into BA values (462, "Дженни Хан");
Insert into BA values (463, "Дженсен Луиза");
Insert into BA values (464, "Джеральд Бром");
Insert into BA values (465, "Джеральд Бром");
Insert into BA values (466, "Джефф Зентнер");
Insert into BA values (467, "Джефф Мариотт");
Insert into BA values (468, "Джиллиан");
Insert into BA values (469, "Джо Шрайбер");
Insert into BA values (470, "Джон Ле Карре");
Insert into BA values (471, "Джон Ле Карре");
Insert into BA values (472, "Джон Миллер");
Insert into BA values (473, "Джонатан Барнс");
Insert into BA values (473, "Кейт Хартфилд");
Insert into BA values (473, "Фоз Медоуз");
Insert into BA values (473, "Эдриан Чайковски");
Insert into BA values (473, "Эмма Ньюман");
Insert into BA values (474, "Джонатан Литем");
Insert into BA values (475, "Джонатан Стрэн");
Insert into BA values (476, "Джонатан Троппер");
Insert into BA values (477, "Джонс Стивен");
Insert into BA values (478, "Джордж Р.Р. Мартин");
Insert into BA values (479, "Джоуи Грасеффа");
Insert into BA values (480, "Джули Си Дао");
Insert into BA values (481, "Диккенс Чарлз");
Insert into BA values (482, "Диккенс Чарлз");
Insert into BA values (483, "Диккенс Чарлз");
Insert into BA values (484, "Дина Оттом");
Insert into BA values (485, "Дозуа Гарднер");
Insert into BA values (486, "Дойл Артур Конан");
Insert into BA values (487, "Дойл Артур Конан");
Insert into BA values (488, "Дойл Артур Конан");
Insert into BA values (489, "Долан Джон");
Insert into BA values (490, "Долин Антон Владимирович");
Insert into BA values (491, "Долинин Александр");
Insert into BA values (492, "Доминик Сильвен");
Insert into BA values (493, "Дониэль Клейтон");
Insert into BA values (494, "Донна Тартт");
Insert into BA values (495, "Донован Джеймс");
Insert into BA values (496, "Достоевский Федор Михайлович");
Insert into BA values (497, "Достоевский Федор Михайлович");
Insert into BA values (498, "Достоевский Федор Михайлович");
Insert into BA values (499, "Достоевский Федор Михайлович");
Insert into BA values (500, "Достоевский Федор Михайлович");
Insert into BA values (501, "Достоевский Федор Михайлович");
Insert into BA values (502, "Достоевский Федор Михайлович");
Insert into BA values (503, "Достоевский Федор Михайлович");
Insert into BA values (504, "Доусон Люси");
Insert into BA values (505, "Драгунский В.Ю.");
Insert into BA values (505, "Драгунский Д.В.");
Insert into BA values (506, "Драгунский Денис Викторович");
Insert into BA values (507, "Драгунский Денис Викторович");
Insert into BA values (508, "Драйзер Теодор");
Insert into BA values (509, "Драйзер Теодор");
Insert into BA values (510, "Джеймс Госс");
Insert into BA values (510, "Дуглас Адамс");
Insert into BA values (510, "Дэвид Фишер");
Insert into BA values (511, "Дэвид Бишофф");
Insert into BA values (511, "Роберт Шекли");
Insert into BA values (512, "Дэвид Брин");
Insert into BA values (513, "Дэвид Геммел");
Insert into BA values (514, "Дэвид Геммел");
Insert into BA values (515, "Дэйв Хатчинсон");
Insert into BA values (516, "Дэн Симмонс");
Insert into BA values (517, "Дэн Симмонс");
Insert into BA values (518, "Дэн Симмонс");
Insert into BA values (519, "Дэниел Уоллес");
Insert into BA values (520, "Дэниэл Суарез");
Insert into BA values (521, "Дэшнер Джеймс");
Insert into BA values (522, "Дэшнер Джеймс");
Insert into BA values (523, "Дэшнер Джеймс");
Insert into BA values (524, "Дэшнер Джеймс");
Insert into BA values (525, "Дюма Александр");
Insert into BA values (526, "Дюма Александр");
Insert into BA values (527, "Дюма Александр");
Insert into BA values (528, "Дюма Александр");
Insert into BA values (529, "Дюморье Дафна");
Insert into BA values (530, "Е. Бунимович");
Insert into BA values (531, "Ева Никольская");
Insert into BA values (531, "Кристина Зимняя");
Insert into BA values (532, "Евгения Спащенко");
Insert into BA values (533, "Евсеев Вадим Валентинович");
Insert into BA values (534, "Екатерина Богданова");
Insert into BA values (535, "Елена Боннэр");
Insert into BA values (536, "Елена Ершова");
Insert into BA values (537, "Еремеев Артем");
Insert into BA values (538, "Ермаков Дмитрий Сергеевич");
Insert into BA values (539, "Ермаков Дмитрий Сергеевич");
Insert into BA values (540, "Ефремов Иван Антонович");
Insert into BA values (541, "Ефремов Иван Антонович");
Insert into BA values (542, "Жан-Поль Дидьелоран");
Insert into BA values (543, "Желунов Н.А.");
Insert into BA values (544, "Желунов Николай");
Insert into BA values (545, "Живова Татьяна Викторовна");
Insert into BA values (546, "Гаврилов Павел Владимирович");
Insert into BA values (546, "Живова Татьяна Викторовна");
Insert into BA values (547, "Жоэль Диккер");
Insert into BA values (548, "Жоэль Диккер");
Insert into BA values (549, "Забусов Александр");
Insert into BA values (550, "Загребельный Павел");
Insert into BA values (551, "Зайцев Виктор Викторович");
Insert into BA values (552, "Замятин Евгений Иванович");
Insert into BA values (553, "Замятин Евгений Иванович");
Insert into BA values (554, "Замятин Евгений Иванович");
Insert into BA values (555, "Бачило А.Г.");
Insert into BA values (555, "Белаш А.М.");
Insert into BA values (555, "Белаш Людмила");
Insert into BA values (555, "де Клемешье Алекс");
Insert into BA values (555, "Зарубина Д.Н.");
Insert into BA values (555, "Каганов Л.А.");
Insert into BA values (555, "Лукьяненко С.В.");
Insert into BA values (555, "Остапенко Ю.В.");
Insert into BA values (555, "Резанова Н.В.");
Insert into BA values (555, "Тырин М.Ю.");
Insert into BA values (556, "Злотников Роман");
Insert into BA values (557, "Зои Сагг");
Insert into BA values (558, "Золя Эмиль");
Insert into BA values (559, "Зощенко Михаил Михайлович");
Insert into BA values (560, "Зощенко Михаил Михайлович");
Insert into BA values (561, "Ив Престон");
Insert into BA values (562, "Иванов Алексей Викторович");
Insert into BA values (563, "Иванов Алексей Викторович");
Insert into BA values (564, "Иванов Алексей Викторович");
Insert into BA values (565, "Иванов Алексей Викторович");
Insert into BA values (566, "Иванов Алексей Викторович");
Insert into BA values (567, "Иванов Алексей Викторович");
Insert into BA values (568, "Иванов Алексей Викторович");
Insert into BA values (569, "Ида Мартин");
Insert into BA values (570, "Ильф Илья");
Insert into BA values (570, "Петров Евгений");
Insert into BA values (571, "Ильф Илья");
Insert into BA values (571, "Петров Евгений");
Insert into BA values (572, "Ильф Илья");
Insert into BA values (572, "Петров Евгений");
Insert into BA values (573, "Иннес Майкл");
Insert into BA values (574, "Ирина Котова");
Insert into BA values (575, "Ирина Шевченко");
Insert into BA values (576, "Ирина Ясина");
Insert into BA values (577, "Йон Колфер");
Insert into BA values (578, "К. Медведевич");
Insert into BA values (579, "Кабир Максим Ахмадович");
Insert into BA values (580, "Кавалли Нина");
Insert into BA values (581, "Кай Майер");
Insert into BA values (582, "Калашников М.Т.");
Insert into BA values (583, "Калбазов Константин");
Insert into BA values (584, "Калинкина Анна Владимировна");
Insert into BA values (585, "Калинкина Анна Владимировна");
Insert into BA values (586, "Калмыков Александр Владимирович");
Insert into BA values (587, "Каменев Алекс");
Insert into BA values (588, "Камю Альбер");
Insert into BA values (589, "Камю Альбер");
Insert into BA values (590, "Камю Альбер");
Insert into BA values (591, "Камю Альбер");
Insert into BA values (592, "Каннинг Виктор");
Insert into BA values (593, "Кантор");
Insert into BA values (594, "Карамзин Николай Михайлович");
Insert into BA values (594, "Ключевский Василий Осипович");
Insert into BA values (594, "Соловьев Сергей Михайлович");
Insert into BA values (595, "Карасюк Д.Ю.");
Insert into BA values (596, "Карина Бартш");
Insert into BA values (597, "Карина Демина");
Insert into BA values (598, "Карлсон Джефф");
Insert into BA values (599, "Каспари Вера");
Insert into BA values (600, "Кассандра Клэр");
Insert into BA values (601, "Кассандра Клэр");
Insert into BA values (602, "Кассандра Клэр");
Insert into BA values (603, "Кассандра Клэр");
Insert into BA values (604, "Кассандра Клэр");
Insert into BA values (605, "Кафка Франц");
Insert into BA values (606, "Баучер Энтони");
Insert into BA values (606, "Квентин Патрик");
Insert into BA values (606, "Стагге Джонатан");
Insert into BA values (607, "Дэниэл Уоллес");
Insert into BA values (607, "Кевин Андерсон");
Insert into BA values (608, "Кейт Мур");
Insert into BA values (609, "Келли Ванесса");
Insert into BA values (610, "Кельман Даниэль");
Insert into BA values (611, "Кем Нанн");
Insert into BA values (612, "Кен Маклауд");
Insert into BA values (613, "Керри Манискалко");
Insert into BA values (614, "Кертман Л.Л.");
Insert into BA values (615, "Кинг Стивен");
Insert into BA values (616, "Кинг Стивен");
Insert into BA values (617, "Кинг Стивен");
Insert into BA values (618, "Кинг Стивен");
Insert into BA values (619, "Кинг Стивен");
Insert into BA values (620, "Кинг Стивен");
Insert into BA values (621, "Кинг Стивен");
Insert into BA values (622, "Кинг Стивен");
Insert into BA values (623, "Кинг Стивен");
Insert into BA values (624, "Кинг Стивен");
Insert into BA values (625, "Кинг Стивен");
Insert into BA values (626, "Кинг Стивен");
Insert into BA values (627, "Кинг Стивен");
Insert into BA values (628, "Кинг Стивен");
Insert into BA values (629, "Кинг Стивен");
Insert into BA values (630, "Кинг Стивен");
Insert into BA values (631, "Кинг Стивен");
Insert into BA values (632, "Кинг Стивен");
Insert into BA values (633, "Кинг Стивен");
Insert into BA values (634, "Кинг Стивен");
Insert into BA values (635, "Кинг Стивен");
Insert into BA values (636, "Кинг Стивен");
Insert into BA values (637, "Кинг Стивен");
Insert into BA values (638, "Кинг Стивен");
Insert into BA values (639, "Кинг Стивен");
Insert into BA values (640, "Кинг Стивен");
Insert into BA values (641, "Кинг Стивен");
Insert into BA values (642, "Кинг Стивен");
Insert into BA values (643, "Кинг Стивен");
Insert into BA values (644, "Кинг Стивен");
Insert into BA values (645, "Кинг Стивен");
Insert into BA values (646, "Кинг Стивен");
Insert into BA values (647, "Кинг Стивен");
Insert into BA values (648, "Кинг Стивен");
Insert into BA values (649, "Кинг Стивен");
Insert into BA values (650, "Кинг Стивен");
Insert into BA values (651, "Кинг Стивен");
Insert into BA values (652, "Кинг Стивен");
Insert into BA values (653, "Кинг Стивен");
Insert into BA values (654, "Кинг Стивен");
Insert into BA values (655, "Кинг Стивен");
Insert into BA values (656, "Кинг Стивен");
Insert into BA values (657, "Кинг Стивен");
Insert into BA values (658, "Кинг Стивен");
Insert into BA values (659, "Кинг Стивен");
Insert into BA values (660, "Кинг Стивен");
Insert into BA values (661, "Кинг Стивен");
Insert into BA values (662, "Кинг Стивен");
Insert into BA values (663, "Кинг Стивен");
Insert into BA values (664, "Кинг Стивен");
Insert into BA values (665, "Кинг Стивен");
Insert into BA values (666, "Кинг Стивен");
Insert into BA values (667, "Кинг Стивен");
Insert into BA values (668, "Кинг Стивен");
Insert into BA values (669, "Кинг Стивен");
Insert into BA values (670, "Кинг Стивен");
Insert into BA values (671, "Кинг Стивен");
Insert into BA values (672, "Кинг Стивен");
Insert into BA values (673, "Кинг Стивен");
Insert into BA values (674, "Кинг Стивен");
Insert into BA values (675, "Кинг Стивен");
Insert into BA values (676, "Кинг Стивен");
Insert into BA values (677, "Кинг Стивен");
Insert into BA values (678, "Кинг Стивен");
Insert into BA values (679, "Кинг Стивен");
Insert into BA values (680, "Кинг Стивен");
Insert into BA values (681, "Кинг Стивен");
Insert into BA values (682, "Кинг Стивен");
Insert into BA values (683, "Кинг Стивен");
Insert into BA values (684, "Кинг Стивен");
Insert into BA values (685, "Кинг Стивен");
Insert into BA values (686, "Кинг Стивен");
Insert into BA values (687, "Кинг Стивен");
Insert into BA values (688, "Кинг Стивен");
Insert into BA values (689, "Кинг Стивен");
Insert into BA values (690, "Кинг Стивен");
Insert into BA values (691, "Кинг Стивен");
Insert into BA values (692, "Кинг Стивен");
Insert into BA values (693, "Кинг Стивен");
Insert into BA values (694, "Кинг Стивен");
Insert into BA values (695, "Кира Стрельникова");
Insert into BA values (696, "Кирстен Уайт");
Insert into BA values (697, "Кит Де Кандидо");
Insert into BA values (698, "Кит Де Кандидо");
Insert into BA values (699, "Китон Дайан");
Insert into BA values (700, "Клайн Эрнест");
Insert into BA values (701, "Кларк Люси");
Insert into BA values (702, "Кликин");
Insert into BA values (702, "Михаил Геннадьевич.");
Insert into BA values (703, "Клэр Кассандра");
Insert into BA values (704, "Ключевский В.О.");
Insert into BA values (705, "Ключевский Василий Осипович");
Insert into BA values (705, "Платонов С.");
Insert into BA values (705, "Погодин Михаил Петрович");
Insert into BA values (705, "Фирсов Н.");
Insert into BA values (706, "Коваль Ярослав");
Insert into BA values (707, "Коган З.Л.");
Insert into BA values (708, "Коди Кеплингер");
Insert into BA values (709, "Кожевников Олег");
Insert into BA values (710, "Авдюхина Софи");
Insert into BA values (710, "Козинаки Марина");
Insert into BA values (711, "Галина Лонгиновна");
Insert into BA values (711, "Козловская");
Insert into BA values (712, "Кокоулин Андрей Алексеевич");
Insert into BA values (713, "Коллинз Сьюзен");
Insert into BA values (714, "Коллинз Уилки");
Insert into BA values (715, "Коллинз Уилки");
Insert into BA values (716, "Комбат Найтов");
Insert into BA values (717, "Конецкий Виктор Викторович");
Insert into BA values (718, "Коннелли Майкл");
Insert into BA values (719, "Конычев Игорь");
Insert into BA values (720, "Кортасар Хулио");
Insert into BA values (721, "Кортасар Хулио");
Insert into BA values (722, "Косухина Наталья Викторовна");
Insert into BA values (723, "Котова Ирина");
Insert into BA values (724, "Коултер");
Insert into BA values (725, "Кофф Натализа");
Insert into BA values (726, "Коэльо Пауло");
Insert into BA values (727, "Коэльо Пауло");
Insert into BA values (728, "Коэльо Пауло");
Insert into BA values (729, "Красницкий Евгений Сергеевич");
Insert into BA values (730, "Варюшенков Денис Евгеньевич");
Insert into BA values (730, "Красницкий Евгений Сергеевич");
Insert into BA values (731, "Град Ирина");
Insert into BA values (731, "Красницкий Евгений Сергеевич");
Insert into BA values (731, "Кузнецова Елена Анатольевна");
Insert into BA values (732, "Кристина Старк");
Insert into BA values (733, "Кристофер Голден");
Insert into BA values (734, "Кристофер Голден");
Insert into BA values (735, "Кристофер Прист");
Insert into BA values (736, "Кружевский Дмитрий");
Insert into BA values (737, "Крузи Дженнифер");
Insert into BA values (738, "Абинякин Р. М.");
Insert into BA values (738, "Калиткина Н. Л.");
Insert into BA values (738, "Комаровский Е. А.");
Insert into BA values (738, "Кручинин А.С.");
Insert into BA values (738, "Кузнецов Н. А.");
Insert into BA values (738, "Марыняк А.В.");
Insert into BA values (738, "Петров А. А.");
Insert into BA values (738, "Трамбицкий Ю. А.");
Insert into BA values (739, "Крэнстон Б.");
Insert into BA values (740, "Ксения Хан");
Insert into BA values (741, "Кудрова Ирма Викторовна");
Insert into BA values (742, "Кузнецов Сергей Юрьевич");
Insert into BA values (743, "Кузнецова Г.Н.");
Insert into BA values (744, "Кузнецова Светлана Александровна");
Insert into BA values (745, "Кулик Степан");
Insert into BA values (746, "Кун Н.А.");
Insert into BA values (747, "Куприн Александр Иванович");
Insert into BA values (748, "Куприн Александр Иванович");
Insert into BA values (749, "Кучерская М.А.");
Insert into BA values (750, "Кшиштоф Пискорский");
Insert into BA values (751, "Кэннон Джоанна");
Insert into BA values (752, "Кэннон Джоанна");
Insert into BA values (753, "Кэтрин М. Валенте");
Insert into BA values (754, "Кэтрин М. Валенте");
Insert into BA values (755, "Лавкрафт Говард Филлипс");
Insert into BA values (756, "Лавкрафт Говард Филлипс");
Insert into BA values (757, "Лавкрафт Говард Филлипс");
Insert into BA values (758, "Говард Филлипс");
Insert into BA values (758, "Лавкрафт");
Insert into BA values (759, "Лао-цзы");
Insert into BA values (760, "Ле Карре Джон");
Insert into BA values (761, "Леббон Тим");
Insert into BA values (762, "Лебедев Виктор Робертович");
Insert into BA values (763, "Лебовски Редгрейн");
Insert into BA values (764, "Лем С.");
Insert into BA values (765, "Лем Станислав");
Insert into BA values (766, "Лем Станислав");
Insert into BA values (767, "Лем Станислав");
Insert into BA values (768, "Леоненко Дмитрий");
Insert into BA values (769, "Леонов А.А.");
Insert into BA values (770, "Лер Дик");
Insert into BA values (771, "Лермонтов Михаил Юрьевич");
Insert into BA values (772, "Лернер Марик");
Insert into BA values (773, "Леру Гастон");
Insert into BA values (774, "Лехчина Яна");
Insert into BA values (775, "Ли Бардуго");
Insert into BA values (776, "Ли Бардуго");
Insert into BA values (777, "Ли Бардуго");
Insert into BA values (778, "Ли Бардуго");
Insert into BA values (779, "Ли Бардуго");
Insert into BA values (780, "Либба Брэй");
Insert into BA values (781, "Ливергант Александр Яковлевич");
Insert into BA values (782, "Литвиненко Елена Ивановна");
Insert into BA values (783, "Лихачев Д.С.");
Insert into BA values (784, "Лондон Джек");
Insert into BA values (785, "Лондон Джек");
Insert into BA values (786, "Лондон Джек");
Insert into BA values (787, "Лондон Джек");
Insert into BA values (788, "Лопатин Георгий");
Insert into BA values (789, "Лора Радзиевская");
Insert into BA values (790, "Лорен Кейт");
Insert into BA values (791, "Лорен Кейт");
Insert into BA values (792, "Лорен Кейт");
Insert into BA values (793, "Луженский Денис Андреевич");
Insert into BA values (794, "Лукьяненко С.В.");
Insert into BA values (795, "Лукьяненко С.В.");
Insert into BA values (796, "Лукьяненко Сергей Васильевич");
Insert into BA values (797, "Лукьяненко Сергей Васильевич");
Insert into BA values (798, "Лукьяненко Сергей Васильевич");
Insert into BA values (799, "Лукьяненко Сергей Васильевич");
Insert into BA values (800, "Лукьяненко Сергей Васильевич");
Insert into BA values (801, "Лукьяненко Сергей Васильевич");
Insert into BA values (802, "Лукьяненко Сергей Васильевич");
Insert into BA values (803, "Лукьяненко Сергей Васильевич");
Insert into BA values (804, "Лукьяненко Сергей Васильевич");
Insert into BA values (805, "Лукьяненко Сергей Васильевич");
Insert into BA values (806, "Лукьяненко Сергей Васильевич");
Insert into BA values (807, "Лукьяненко Сергей Васильевич");
Insert into BA values (808, "Лукьяненко Сергей Васильевич");
Insert into BA values (809, "Васильев Владимир Николаевич");
Insert into BA values (809, "Лукьяненко Сергей Васильевич");
Insert into BA values (810, "Громов Александр Николаевич");
Insert into BA values (810, "Лукьяненко Сергей Васильевич");
Insert into BA values (811, "Лукьяненко Сергей Васильевич");
Insert into BA values (812, "Лукьяненко Сергей");
Insert into BA values (813, "Лысак Сергей Васильевич");
Insert into BA values (814, "Лысак Сергей Васильевич");
Insert into BA values (815, "Лысак Сергей Васильевич");
Insert into BA values (816, "Лысак Сергей Васильевич");
Insert into BA values (817, "Лю Кен");
Insert into BA values (818, "Мазин Александр Владимирович");
Insert into BA values (819, "Майер Стефани");
Insert into BA values (820, "Майер Стефани");
Insert into BA values (821, "Майер Стефани");
Insert into BA values (822, "Майер Стефани");
Insert into BA values (823, "Майкл Муркок");
Insert into BA values (824, "Макаренко Антон Семенович");
Insert into BA values (825, "Маккалоу Колин");
Insert into BA values (826, "Маккалоу Колин");
Insert into BA values (827, "Маккалоу Колин");
Insert into BA values (828, "Маккалоу Колин");
Insert into BA values (829, "Маккалоу Колин");
Insert into BA values (830, "Маккалоу Колин");
Insert into BA values (831, "Маккалоу Колин");
Insert into BA values (832, "Маккаммон Роберт");
Insert into BA values (833, "Макнот Джудит");
Insert into BA values (834, "Макс Фрай");
Insert into BA values (835, "Макс Фрай");
Insert into BA values (836, "Макс Фрай");
Insert into BA values (837, "Макс Фрай");
Insert into BA values (838, "Макс Фрай");
Insert into BA values (839, "Макс Фрай");
Insert into BA values (840, "Макс Фрай");
Insert into BA values (841, "Макс Фрай");
Insert into BA values (842, "Макс Фрай");
Insert into BA values (843, "Макс Фрай");
Insert into BA values (844, "Макс Фрай");
Insert into BA values (845, "Макс Фрай");
Insert into BA values (846, "Макс Фрай");
Insert into BA values (847, "Макс Фрай");
Insert into BA values (848, "Макс Фрай");
Insert into BA values (849, "Максим Горький");
Insert into BA values (850, "Максим Марух");
Insert into BA values (851, "Максимов Рустам");
Insert into BA values (852, "Максимушкин Андрей");
Insert into BA values (853, "Малиновская Елена Михайловна");
Insert into BA values (854, "Мамонтов С.И.");
Insert into BA values (855, "Мандельштам Осип Эмильевич");
Insert into BA values (856, "Манн Томас");
Insert into BA values (857, "Манн Томас");
Insert into BA values (858, "Манн Томас");
Insert into BA values (859, "Манн Томас");
Insert into BA values (860, "Манн Томас");
Insert into BA values (861, "Манн Томас");
Insert into BA values (862, "Маргарет Штоль");
Insert into BA values (863, "Марина Эльденберт");
Insert into BA values (864, "Марисса Мейер");
Insert into BA values (865, "Марисса Мейер");
Insert into BA values (866, "Марисса Мейер");
Insert into BA values (867, "Марисса Мейер");
Insert into BA values (868, "Мария Боталова");
Insert into BA values (869, "Мария Боталова");
Insert into BA values (870, "Мария Дэвана Хэдли");
Insert into BA values (871, "Мария Дэвана Хэдли");
Insert into BA values (872, "Мария Степанова");
Insert into BA values (873, "Марк Керасини");
Insert into BA values (874, "Марк Яковлев");
Insert into BA values (875, "Маркус Хёрн");
Insert into BA values (876, "Мартин Джордж Р. Р.");
Insert into BA values (877, "Мартин Джордж Р. Р.");
Insert into BA values (878, "Мартин Джордж Р. Р.");
Insert into BA values (879, "Мартин Джордж Р. Р.");
Insert into BA values (880, "Мартин Джордж Р.Р.");
Insert into BA values (881, "Мартин Джордж Р.Р.");
Insert into BA values (882, "Мартин Джордж Р.Р.");
Insert into BA values (883, "Мартин Джордж Р.Р.");
Insert into BA values (884, "Мартин Джордж Р.Р.");
Insert into BA values (885, "Мартин Джордж Р.Р.");
Insert into BA values (886, "Мартин Джордж Р.Р.");
Insert into BA values (887, "Мартин Джордж Р.Р.");
Insert into BA values (888, "Мартин Джордж Р.Р.");
Insert into BA values (889, "Мартин Джордж Р.Р.");
Insert into BA values (890, "Дозуа Гарднер");
Insert into BA values (890, "Мартин Джордж");
Insert into BA values (891, "Марш Найо");
Insert into BA values (892, "Матвеев Владимир");
Insert into BA values (893, "Матвеева Анна");
Insert into BA values (894, "Матвеева Анна");
Insert into BA values (895, "Мафи Тахира");
Insert into BA values (896, "Мафи Тахира");
Insert into BA values (897, "Мах Макс");
Insert into BA values (898, "Мах Макс");
Insert into BA values (899, "Машкова Анастасия Владимировна");
Insert into BA values (900, "Мелвилл Герман");
Insert into BA values (901, "Мелисса Алберт");
Insert into BA values (902, "Мельников Руслан Викторович");
Insert into BA values (903, "Мельников Руслан Викторович");
Insert into BA values (904, "Мельников-Печерский Павел Иванович");
Insert into BA values (905, "Мессерер Борис Асафович");
Insert into BA values (906, "Миллер Джон");
Insert into BA values (907, "Миллер-младший Уолтер");
Insert into BA values (908, "Минаков Игорь Валерьевич");
Insert into BA values (909, "Минский Марвин");
Insert into BA values (910, "Миропольский Дмитрий");
Insert into BA values (911, "Миропольский Дмитрий Владимирович");
Insert into BA values (912, "Митчелл Глэдис");
Insert into BA values (913, "Михаил Атаманов");
Insert into BA values (914, "Михаил Бродский");
Insert into BA values (915, "Михайловский Александр Борисович");
Insert into BA values (915, "Харников Александр Петрович");
Insert into BA values (916, "Михайловский Александр Борисович");
Insert into BA values (916, "Харников Александр Петрович");
Insert into BA values (917, "Михайловский Александр Борисович");
Insert into BA values (917, "Харников Александр Петрович");
Insert into BA values (918, "Михайловский Александр");
Insert into BA values (918, "Харников Александр Петрович");
Insert into BA values (919, "Михайловский Александр");
Insert into BA values (919, "Харников Александр Петрович");
Insert into BA values (920, "Михайловский Александр");
Insert into BA values (920, "Харников Александр Петрович");
Insert into BA values (921, "Михеев Михаил Александрович");
Insert into BA values (922, "Мишин Виктор");
Insert into BA values (923, "Можейко И.В.");
Insert into BA values (924, "Мойес Патрисия");
Insert into BA values (925, "Монахиня Ефимия");
Insert into BA values (926, "Морган Мэтсон");
Insert into BA values (927, "Мордюкова Н.В.");
Insert into BA values (928, "Морин Гу");
Insert into BA values (929, "Морин Джонсон");
Insert into BA values (930, "Моруа Андре");
Insert into BA values (931, "Москвин Сергей Львович");
Insert into BA values (932, "Моэм Сомерсет");
Insert into BA values (933, "Моэм Сомерсет");
Insert into BA values (934, "Моэм Сомерсет");
Insert into BA values (935, "Моэм Сомерсет");
Insert into BA values (936, "Моэм Сомерсет");
Insert into BA values (937, "Мэри Лю");
Insert into BA values (938, "Мэри Э. Пирсон");
Insert into BA values (939, "Мэри Э. Пирсон");
Insert into BA values (940, "Мэтт Грейнинг");
Insert into BA values (941, "Мясоедов Владимир");
Insert into BA values (942, "Найтов Комбат");
Insert into BA values (943, "Найтов Комбат");
Insert into BA values (944, "Найтов Комбат");
Insert into BA values (945, "Наринэ Абгарян");
Insert into BA values (946, "Наринэ Абгарян");
Insert into BA values (947, "Нежинский Александр");
Insert into BA values (948, "Некрасов Николай Алексеевич");
Insert into BA values (949, "Некрасов Николай Алексеевич");
Insert into BA values (950, "Нестерова Наталья");
Insert into BA values (951, "Нестерова Наталья");
Insert into BA values (952, "Нечаева Наталья");
Insert into BA values (953, "Нивен Дженнифер");
Insert into BA values (954, "Виктория Шваб и др.");
Insert into BA values (954, "Никола Юн");
Insert into BA values (955, "Николаев Игорь Юрьевич");
Insert into BA values (956, "Николаенко Александра Вадимовна");
Insert into BA values (957, "Никольская Ева Геннадьевна");
Insert into BA values (958, "Никулин Николай Николаевич");
Insert into BA values (959, "Никулин Ю.В.");
Insert into BA values (960, "Нил Гейман");
Insert into BA values (961, "Нил Гейман");
Insert into BA values (962, "Нил Гейман");
Insert into BA values (963, "Нил Гейман");
Insert into BA values (964, "Нил Гейман");
Insert into BA values (965, "Ной Хоули");
Insert into BA values (966, "О. Генри");
Insert into BA values (967, "О`Рурк Эрика");
Insert into BA values (968, "Обиома Чигози");
Insert into BA values (969, "Обручев Владимир Афанасьевич");
Insert into BA values (970, "Оксана Забужко");
Insert into BA values (971, "Олли Вингет");
Insert into BA values (972, "Ольга Валентеева");
Insert into BA values (973, "Ольга Валентеева");
Insert into BA values (974, "Ольга Куно");
Insert into BA values (975, "Ольга Романовская");
Insert into BA values (976, "Ольга Романовская");
Insert into BA values (977, "Оруэлл Джордж");
Insert into BA values (978, "Оруэлл Джордж");
Insert into BA values (979, "Оруэлл Джордж");
Insert into BA values (980, "Оруэлл Джордж");
Insert into BA values (981, "Осипов Алексей Ильич");
Insert into BA values (982, "Остен Джейн");
Insert into BA values (983, "Остен Джейн");
Insert into BA values (984, "Остен Джейн");
Insert into BA values (985, "Островский Александр Николаевич");
Insert into BA values (986, "Островский Николай Алексеевич");
Insert into BA values (987, "Павел Макаров");
Insert into BA values (988, "Павел Финн");
Insert into BA values (989, "Панколь Катрин");
Insert into BA values (990, "Панколь Катрин");
Insert into BA values (991, "Бустос Мигель");
Insert into BA values (991, "Пантоха Оскар");
Insert into BA values (992, "Пастернак Б.Л.");
Insert into BA values (993, "Пастернак Борис Леонидович");
Insert into BA values (994, "Пастернак Борис Леонидович");
Insert into BA values (995, "Пашнина Ольга Олеговна");
Insert into BA values (996, "Пейчева Анна Михайловна");
Insert into BA values (997, "Пёрсиг Роберт");
Insert into BA values (998, "Пирс Йен");
Insert into BA values (999, "Питер Дэвид");
Insert into BA values (1000, "Питер Клайнс");
Insert into BA values (1001, "Питер Менделсунд");
Insert into BA values (1002, "Питер Уоттс");
Insert into BA values (1003, "Питер Уоттс");
Insert into BA values (1004, "Платон");
Insert into BA values (1005, "Плетнев Александр Владимирович");
Insert into BA values (1006, "Плетнев Александр Владимирович");
Insert into BA values (1007, "Плисецкий Азарий Михайлович");
Insert into BA values (1008, "По Эдгар Аллан");
Insert into BA values (1009, "По Эдгар Аллан");
Insert into BA values (1010, "Побережник Николай");
Insert into BA values (1011, "Побережник Николай");
Insert into BA values (1012, "Подрабинек Александр Пинхосович");
Insert into BA values (1013, "Познер В.В.");
Insert into BA values (1014, "Познер В.В.");
Insert into BA values (1015, "Пол Крилли");
Insert into BA values (1016, "Поляков Влад");
Insert into BA values (1017, "Поляков Юрий");
Insert into BA values (1018, "Поляков Юрий Михайлович");
Insert into BA values (1019, "Поляков Юрий Михайлович");
Insert into BA values (1020, "Поляков Юрий Михайлович");
Insert into BA values (1021, "Поляков Юрий Михайлович");
Insert into BA values (1022, "Поляков Юрий Михайлович");
Insert into BA values (1023, "Полякова Маргарита");
Insert into BA values (1024, "Полякова Маргарита");
Insert into BA values (1025, "Поселягин Владимир");
Insert into BA values (1026, "Поселягин Владимир Геннадьевич");
Insert into BA values (1027, "Поселягин Владимир Геннадьевич");
Insert into BA values (1028, "Поселягин Владимир Геннадьевич");
Insert into BA values (1029, "Поселягин Владимир Геннадьевич");
Insert into BA values (1030, "Посняков Андрей Анатольевич");
Insert into BA values (1031, "Посняков Андрей Анатольевич");
Insert into BA values (1032, "Посняков Андрей Анатольевич");
Insert into BA values (1033, "Поспелова Екатерина Глебовна");
Insert into BA values (1034, "Прайс Роберт М.");
Insert into BA values (1035, "Прах Вячеслав");
Insert into BA values (1036, "Прах Вячеслав");
Insert into BA values (1037, "Престон Ив");
Insert into BA values (1038, "Прозоров Александр Дмитриевич");
Insert into BA values (1039, "Пронин");
Insert into BA values (1040, "Пьянкова Карина");
Insert into BA values (1041, "Раабе Мелани");
Insert into BA values (1042, "Радзинский Э.С.");
Insert into BA values (1043, "Радзинский Э.С.");
Insert into BA values (1044, "Радзинский Э.С.");
Insert into BA values (1045, "Радзинский Э.С.");
Insert into BA values (1046, "Радзинский Э.С.");
Insert into BA values (1047, "Радзинский Э.С.");
Insert into BA values (1048, "Разумовский Л.С.");
Insert into BA values (1049, "Райан Гродин");
Insert into BA values (1050, "Райли Люсинда");
Insert into BA values (1051, "Раневская Ф.Г.");
Insert into BA values (1052, "Распутин Валентин Григорьевич");
Insert into BA values (1053, "Распутин Валентин Григорьевич");
Insert into BA values (1054, "Распутин Валентин Григорьевич");
Insert into BA values (1055, "Расселл Брэнд");
Insert into BA values (1056, "Расселл Ромина");
Insert into BA values (1057, "Ремарк Эрих Мария");
Insert into BA values (1058, "Ремарк Эрих Мария");
Insert into BA values (1059, "Ремарк Эрих Мария");
Insert into BA values (1060, "Ремарк Эрих Мария");
Insert into BA values (1061, "Ремарк Эрих Мария");
Insert into BA values (1062, "Ремарк Эрих Мария");
Insert into BA values (1063, "Ремарк Эрих Мария");
Insert into BA values (1064, "Ремарк Эрих Мария");
Insert into BA values (1065, "Ремарк Эрих Мария");
Insert into BA values (1066, "Ремарк Эрих Мария");
Insert into BA values (1067, "Ремарк Эрих Мария");
Insert into BA values (1068, "Ремарк Эрих Мария");
Insert into BA values (1069, "Ремарк Эрих Мария");
Insert into BA values (1070, "Ремарк Эрих Мария");
Insert into BA values (1071, "Ремарк Эрих Мария");
Insert into BA values (1072, "Ремарк Эрих Мария");
Insert into BA values (1073, "Ремарк Эрих Мария");
Insert into BA values (1074, "Ригби Эл");
Insert into BA values (1075, "Джим Бирд");
Insert into BA values (1075, "Рич Хэндли");
Insert into BA values (1076, "Роберт Битти");
Insert into BA values (1077, "Роберт Ирвин Говард");
Insert into BA values (1078, "Роберт Ирвин Говард");
Insert into BA values (1079, "Роберт Ирвин Говард");
Insert into BA values (1080, "Роберт Ирвин Говард");
Insert into BA values (1081, "Роберт М. Прайс");
Insert into BA values (1082, "Роберт М. Прайс");
Insert into BA values (1083, "Роберт Райан");
Insert into BA values (1084, "Роберт Роупер");
Insert into BA values (1085, "Роговская Дина");
Insert into BA values (1086, "Розмари Салливан");
Insert into BA values (1087, "Рудазов Александр Валентинович");
Insert into BA values (1088, "Рута Шейл");
Insert into BA values (1089, "Рыбаков Анатолий Наумович");
Insert into BA values (1090, "Рэнд Айн");
Insert into BA values (1091, "Савин Влад");
Insert into BA values (1092, "Савин Влад");
Insert into BA values (1093, "Савин Влад");
Insert into BA values (1094, "Савин Влад");
Insert into BA values (1095, "Сагг Зои");
Insert into BA values (1096, "Садулаев Герман Умаралиевич");
Insert into BA values (1097, "Салливан Майкл");
Insert into BA values (1098, "Салливан Майкл");
Insert into BA values (1099, "Салман Рушди");
Insert into BA values (1100, "Салье Михаил Александрович");
Insert into BA values (1101, "Саманта Швеблин");
Insert into BA values (1102, "Сана Валиулина");
Insert into BA values (1103, "Сапковский Анджей");
Insert into BA values (1104, "Сапковский Анджей");
Insert into BA values (1105, "Сапковский Анджей");
Insert into BA values (1106, "Сапковский Анджей");
Insert into BA values (1107, "Сапковский Анджей");
Insert into BA values (1108, "Сапковский Анджей");
Insert into BA values (1109, "Сапковский Анджей");
Insert into BA values (1110, "Сапковский Анджей");
Insert into BA values (1111, "Сапковский Анджей");
Insert into BA values (1112, "Сапковский Анджей");
Insert into BA values (1113, "Сапковский Анджей");
Insert into BA values (1114, "Сапункова Наталья");
Insert into BA values (1115, "Сара Холланд");
Insert into BA values (1116, "Сартр Жан Поль");
Insert into BA values (1117, "Сартр Жан Поль");
Insert into BA values (1118, "Сафарли Эльчин");
Insert into BA values (1119, "Сафон К.Р.");
Insert into BA values (1120, "Сафон Карлос Руис");
Insert into BA values (1121, "Сафон Карлос Руис");
Insert into BA values (1122, "Сафон Карлос Руис");
Insert into BA values (1123, "Сафон Карлос Руис");
Insert into BA values (1124, "Сахаров Василий");
Insert into BA values (1125, "Св Ск Са");
Insert into BA values (1126, "Свержин Владимир");
Insert into BA values (1127, "Семенов Сергей Александрович");
Insert into BA values (1128, "Сенкевич Генрик");
Insert into BA values (1129, "Сервантес Сааведра Мигель де");
Insert into BA values (1130, "Сергей Есенин");
Insert into BA values (1131, "Силлов Дмитрий Олегович");
Insert into BA values (1132, "Силлов Дмитрий Олегович");
Insert into BA values (1133, "Симмонс Дэн");
Insert into BA values (1134, "Симмонс Дэн");
Insert into BA values (1135, "Симмонс Дэн");
Insert into BA values (1136, "Симмонс Дэн");
Insert into BA values (1137, "Скарлетт Томас");
Insert into BA values (1138, "Скворцов Владимир Николаевич");
Insert into BA values (1139, "Скотт Вестерфельд");
Insert into BA values (1140, "Слава Сэ");
Insert into BA values (1141, "Слава Сэ");
Insert into BA values (1142, "Славникова Ольга Александровна");
Insert into BA values (1143, "Слаповский А.И.");
Insert into BA values (1144, "Смайли Джейн");
Insert into BA values (1145, "Смит Доди");
Insert into BA values (1146, "Смолл Бертрис");
Insert into BA values (1147, "Сокол Лена");
Insert into BA values (1148, "Соловьев Сергей Владимирович");
Insert into BA values (1149, "Соловьев Сергей Михайлович");
Insert into BA values (1150, "Сорокин Игорь Владимирович");
Insert into BA values (1151, "Спаркс Николас");
Insert into BA values (1152, "Спаркс Николас");
Insert into BA values (1153, "Спаркс Николас");
Insert into BA values (1154, "Спаркс Николас");
Insert into BA values (1155, "Спаркс Николас");
Insert into BA values (1156, "Спаркс Николас");
Insert into BA values (1157, "Спаркс Николас");
Insert into BA values (1158, "Спаркс Николас");
Insert into BA values (1159, "Спаркс Николас");
Insert into BA values (1160, "Спаркс Николас");
Insert into BA values (1161, "Спаркс Николас");
Insert into BA values (1162, "Спаркс Николас");
Insert into BA values (1163, "Стайлс");
Insert into BA values (1164, "Станиславский Константин Сергеевич");
Insert into BA values (1165, "Старк Кристина");
Insert into BA values (1166, "Стедман М.Л.");
Insert into BA values (1167, "Стейнбек Джон");
Insert into BA values (1168, "Стейнбек Джон");
Insert into BA values (1169, "Стейнбек Джон");
Insert into BA values (1170, "Стейнбек Джон");
Insert into BA values (1171, "Стендаль Фредерик");
Insert into BA values (1172, "Степнова Марина Львовна");
Insert into BA values (1173, "Стефан Петручо");
Insert into BA values (1174, "Стефан Петручо");
Insert into BA values (1175, "Стив Белинг");
Insert into BA values (1176, "Стив Трайб");
Insert into BA values (1177, "Стивен Моффат");
Insert into BA values (1178, "Стил Даниэла");
Insert into BA values (1179, "Стил Даниэла");
Insert into BA values (1180, "Стил Даниэла");
Insert into BA values (1181, "Стил Даниэла");
Insert into BA values (1182, "Стил Даниэла");
Insert into BA values (1183, "Стил Даниэла");
Insert into BA values (1184, "Стил Даниэла");
Insert into BA values (1185, "Стил Даниэла");
Insert into BA values (1186, "Брэм Стокер");
Insert into BA values (1187, "Стоун Ирвинг");
Insert into BA values (1188, "Стоун Ирвинг");
Insert into BA values (1189, "Стрелова Мария Андреевна");
Insert into BA values (1190, "Строгов Тим");
Insert into BA values (1191, "Стронгин В.Л.");
Insert into BA values (1192, "Стругацкий Аркадий Натанович");
Insert into BA values (1192, "Стругацкий Борис Натанович");
Insert into BA values (1193, "Стругацкий Аркадий Натанович");
Insert into BA values (1193, "Стругацкий Борис Натанович");
Insert into BA values (1194, "Стругацкий Аркадий Натанович");
Insert into BA values (1194, "Стругацкий Борис Натанович");
Insert into BA values (1195, "Стругацкий Аркадий");
Insert into BA values (1195, "Стругацкий Борис Натанович");
Insert into BA values (1196, "Стругацкий Аркадий");
Insert into BA values (1196, "Стругацкий Борис Натанович");
Insert into BA values (1197, "Стругацкий Аркадий");
Insert into BA values (1197, "Стругацкий Борис Натанович");
Insert into BA values (1198, "Стругацкий Аркадий");
Insert into BA values (1198, "Стругацкий Борис Натанович");
Insert into BA values (1199, "Субботин Максим");
Insert into BA values (1200, "Султанов Дмитрий Игоревич");
Insert into BA values (1201, "Сушко Ю.М.");
Insert into BA values (1202, "Таис Сотер");
Insert into BA values (1203, "Таланова Галина");
Insert into BA values (1204, "Тармашев Сергей Сергеевич");
Insert into BA values (1205, "Тармашев Сергей Сергеевич");
Insert into BA values (1206, "Тармашев Сергей Сергеевич");
Insert into BA values (1207, "Тармашев Сергей Сергеевич");
Insert into BA values (1208, "Тармашев Сергей Сергеевич");
Insert into BA values (1209, "Тармашев Сергей Сергеевич");
Insert into BA values (1210, "Тармашев Сергей Сергеевич");
Insert into BA values (1211, "Тармашев Сергей Сергеевич");
Insert into BA values (1212, "Татьяна Зингер");
Insert into BA values (1213, "Татьяна Зинина");
Insert into BA values (1214, "Тахир Саба");
Insert into BA values (1215, "Тахир Саба");
Insert into BA values (1216, "Тед Косматка");
Insert into BA values (1217, "Тейлор Лэйни");
Insert into BA values (1218, "Теккерей Уильям Мейкпис");
Insert into BA values (1219, "Теоли Валерий");
Insert into BA values (1220, "Терентьева Наталия Михайловна");
Insert into BA values (1221, "Терентьева Наталия Михайловна");
Insert into BA values (1222, "Терентьева Наталия Михайловна");
Insert into BA values (1223, "Терентьева Наталия Михайловна");
Insert into BA values (1224, "Терри Лу");
Insert into BA values (1225, "Тим Пауэрс");
Insert into BA values (1226, "Тихонов Дмитрий Александрович");
Insert into BA values (1227, "Толкин Д.Р.");
Insert into BA values (1228, "Толкин Д.Р.");
Insert into BA values (1229, "Толкин Джон Рональд Руэл");
Insert into BA values (1230, "Толкин Джон Рональд Руэл");
Insert into BA values (1231, "Толкин Джон Рональд Руэл");
Insert into BA values (1232, "Толкин Джон Рональд Руэл");
Insert into BA values (1233, "Толкин Джон Рональд Руэл");
Insert into BA values (1234, "Толкин Джон Рональд Руэл");
Insert into BA values (1235, "Толкин Джон Рональд Руэл");
Insert into BA values (1236, "Толкин Джон Рональд Руэл");
Insert into BA values (1237, "Толкин Джон Рональд Руэл");
Insert into BA values (1238, "Толкин Джон Рональд Руэл");
Insert into BA values (1239, "Толкин Джон Рональд Руэл");
Insert into BA values (1240, "Толкин Джон Рональд Руэл");
Insert into BA values (1241, "Толкин Джон Рональд Руэл");
Insert into BA values (1242, "Толкин Джон Рональд Руэл");
Insert into BA values (1243, "Толкин Джон Рональд Руэл");
Insert into BA values (1244, "Толкин Джон Рональд Руэл");
Insert into BA values (1245, "Толкин Джон Рональд Руэл");
Insert into BA values (1246, "Толкин Джон Рональд Руэл");
Insert into BA values (1247, "Толкин Джон Рональд Руэл");
Insert into BA values (1248, "Толстая Татьяна Никитична");
Insert into BA values (1249, "Алексей Николаевич Толстой");
Insert into BA values (1250, "Алексей Николаевич Толстой");
Insert into BA values (1251, "Толстой Алексей Николаевич");
Insert into BA values (1252, "Толстой Алексей Николаевич");
Insert into BA values (1253, "Достоевский Ф.М.");
Insert into BA values (1253, "Толстой Л.Н.");
Insert into BA values (1254, "Лев Толстой");
Insert into BA values (1255, "Лев Толстой");
Insert into BA values (1256, "Лев Николаевич Толстой");
Insert into BA values (1257, "Лев Николаевич Толстой");
Insert into BA values (1258, "Толстой Лев Николаевич");
Insert into BA values (1259, "Толстой Лев Николаевич");
Insert into BA values (1260, "Томас Лиготти");
Insert into BA values (1261, "Томпсон Хантер С.");
Insert into BA values (1262, "Точинов Виктор Павлович");
Insert into BA values (1263, "Трофимов Ерофей");
Insert into BA values (1264, "Тургенев Иван Сергеевич");
Insert into BA values (1265, "Тургенев Иван Сергеевич");
Insert into BA values (1266, "Тюфо Марк");
Insert into BA values (1267, "Уайльд Оскар");
Insert into BA values (1268, "Уилки Коллинз");
Insert into BA values (1269, "Уилсон Колин");
Insert into BA values (1270, "Уилсон Роберт Чарльз");
Insert into BA values (1271, "Уильям Риттер");
Insert into BA values (1272, "Уильям Риттер");
Insert into BA values (1273, "Уильям Хоуп Ходжсон");
Insert into BA values (1274, "Уинспир Жаклин");
Insert into BA values (1275, "Уланов Андрей");
Insert into BA values (1276, "Уленгов Юрий Александрович");
Insert into BA values (1277, "Улицкая Людмила Евгеньевна");
Insert into BA values (1278, "Улицкая Людмила Евгеньевна");
Insert into BA values (1279, "Улицкая Людмила Евгеньевна");
Insert into BA values (1280, "Умберто Эко");
Insert into BA values (1281, "Умберто Эко");
Insert into BA values (1282, "Умберто Эко");
Insert into BA values (1283, "Уоррен Эллис");
Insert into BA values (1284, "Уэйр Рут");
Insert into BA values (1285, "Уэйр Рут");
Insert into BA values (1286, "Уэллс Дэн");
Insert into BA values (1287, "Фартинг П.");
Insert into BA values (1288, "Федоров Алексей Александрович");
Insert into BA values (1289, "Феликс Пальма");
Insert into BA values (1290, "Филип Пулман");
Insert into BA values (1291, "Филип Пулман");
Insert into BA values (1292, "Филон Елена");
Insert into BA values (1293, "Филоненко Вадим Анатольевич");
Insert into BA values (1294, "Филоненко Вадим Анатольевич");
Insert into BA values (1295, "Фирсанова Юлия Алексеевна");
Insert into BA values (1296, "Фицджеральд Фрэнсис Скотт");
Insert into BA values (1297, "Фицджеральд Фрэнсис Скотт");
Insert into BA values (1298, "Фицджеральд Фрэнсис Скотт");
Insert into BA values (1299, "Фицджеральд Фрэнсис Скотт");
Insert into BA values (1300, "Флат Екатерина");
Insert into BA values (1301, "Гюстав");
Insert into BA values (1301, "Флобер");
Insert into BA values (1302, "Фоллетт К.");
Insert into BA values (1303, "Фоллетт Кен");
Insert into BA values (1304, "Фоллетт Кен");
Insert into BA values (1305, "Фоллетт Кен");
Insert into BA values (1306, "Фоллетт Кен");
Insert into BA values (1307, "Фоллетт Кен");
Insert into BA values (1308, "Фоллетт Кен");
Insert into BA values (1309, "Фоллетт Кен");
Insert into BA values (1310, "Фоллетт Кен");
Insert into BA values (1311, "Фоллетт Кен");
Insert into BA values (1312, "Фоллетт Кен");
Insert into BA values (1313, "Фоллетт Кен");
Insert into BA values (1314, "Фомичев Алексей Сергеевич");
Insert into BA values (1315, "Фонда Джейн");
Insert into BA values (1316, "Фрай Макс");
Insert into BA values (1317, "Франсин дю Плесси Грей");
Insert into BA values (1318, "Франциска Вудворт");
Insert into BA values (1319, "Франческа Хейг");
Insert into BA values (1320, "Фред Варгас");
Insert into BA values (1321, "Фрей Эли");
Insert into BA values (1322, "Фуэнтес Карлос");
Insert into BA values (1323, "Хайям Омар");
Insert into BA values (1324, "Хаксли Олдос");
Insert into BA values (1325, "Хаксли Олдос");
Insert into BA values (1326, "Хаксли Олдос");
Insert into BA values (1327, "Хаксли Олдос");
Insert into BA values (1328, "Хаксли Олдос");
Insert into BA values (1329, "Халилулаев Анвар Абдулмаджидович");
Insert into BA values (1330, "Халл Ричард");
Insert into BA values (1331, "Хан Дженни");
Insert into BA values (1332, "Харитонов Юрий Владимирович");
Insert into BA values (1333, "Харпер Ли");
Insert into BA values (1334, "Хейер Джорджет");
Insert into BA values (1335, "Хейер Джорджет");
Insert into BA values (1336, "Хейли Артур");
Insert into BA values (1337, "Хейли Артур");
Insert into BA values (1338, "Хейли Артур");
Insert into BA values (1339, "Хейли Артур");
Insert into BA values (1340, "Хейли Артур");
Insert into BA values (1341, "Хейли Артур");
Insert into BA values (1342, "Хейли Артур");
Insert into BA values (1343, "Хейли Артур");
Insert into BA values (1344, "Хейли Артур");
Insert into BA values (1345, "Хейли Артур");
Insert into BA values (1346, "Хейли Артур");
Insert into BA values (1347, "Хеллер Джозеф");
Insert into BA values (1348, "Хемингуэй Эрнест");
Insert into BA values (1349, "Хемингуэй Эрнест");
Insert into BA values (1350, "Хемингуэй Эрнест");
Insert into BA values (1351, "Хемингуэй Эрнест");
Insert into BA values (1352, "Хемингуэй Эрнест");
Insert into BA values (1353, "Хемингуэй Эрнест");
Insert into BA values (1354, "Хемингуэй Эрнест");
Insert into BA values (1355, "Хемингуэй Эрнест");
Insert into BA values (1356, "Хеммингс Люк");
Insert into BA values (1357, "Хендрикс Грир");
Insert into BA values (1358, "Холмогоров Валентин");
Insert into BA values (1359, "Хорсун Максим Дмитриевич");
Insert into BA values (1360, "Хоук Коллин");
Insert into BA values (1361, "Хоук Коллин");
Insert into BA values (1362, "Хоумс Э.М.");
Insert into BA values (1363, "Храмов Виталий");
Insert into BA values (1364, "Храмов Виталий Иванович");
Insert into BA values (1365, "Храмов Виталий Иванович");
Insert into BA values (1366, "Хьюз Кэтрин");
Insert into BA values (1367, "Цвейг Стефан");
Insert into BA values (1368, "Чарлтон Блейк");
Insert into BA values (1369, "Чеботаревская А.Н.");
Insert into BA values (1370, "Чекунов Вадим");
Insert into BA values (1371, "Чемберджи В.Н.");
Insert into BA values (1372, "Черкасов Алексей Тимофеевич");
Insert into BA values (1373, "Чернышевский Николай Гаврилович");
Insert into BA values (1374, "Чехин Сергей Николаевич");
Insert into BA values (1375, "Чехов Антон Павлович");
Insert into BA values (1376, "Чижов Евгений");
Insert into BA values (1377, "Шапочкин Александр Игоревич");
Insert into BA values (1378, "Шарбонно Жоэль");
Insert into BA values (1379, "Шаргунов Сергей Александрович");
Insert into BA values (1380, "Швецова Ольга Сергеевна");
Insert into BA values (1381, "Швецова Ольга Сергеевна");
Insert into BA values (1382, "Шекспир Уильям");
Insert into BA values (1383, "Шекспир Уильям");
Insert into BA values (1384, "Шекспир Уильям");
Insert into BA values (1385, "Шелдон Сидни");
Insert into BA values (1386, "Шелдон Сидни");
Insert into BA values (1387, "Шелдон Сидни");
Insert into BA values (1388, "Шелдон Сидни");
Insert into BA values (1389, "Шелдон Сидни");
Insert into BA values (1390, "Шелдон Сидни");
Insert into BA values (1391, "Шелдон Сидни");
Insert into BA values (1392, "Шелдон Сидни");
Insert into BA values (1393, "Шелдон Сидни");
Insert into BA values (1394, "Шелдон Сидни");
Insert into BA values (1395, "Шелдон Сидни");
Insert into BA values (1396, "Шелдон Сидни");
Insert into BA values (1397, "Шелдон Сидни");
Insert into BA values (1398, "Шелег Игорь Витальевич");
Insert into BA values (1399, "Шемилт Джейн");
Insert into BA values (1400, "Шенгальц Игорь");
Insert into BA values (1401, "Шенгальц Игорь Александрович");
Insert into BA values (1402, "Шепельский Евгений Александрович");
Insert into BA values (1403, "Шкиль Евгений Юрьевич");
Insert into BA values (1404, "Шляхов А.Л.");
Insert into BA values (1405, "Шмелев Иван Сергеевич");
Insert into BA values (1406, "Шмидт Роберт");
Insert into BA values (1407, "Шмитт Гледис");
Insert into BA values (1408, "Шмитт Гледис");
Insert into BA values (1409, "Шолохов Михаил Александрович");
Insert into BA values (1410, "Шолохов Михаил Александрович");
Insert into BA values (1411, "Шолохов Михаил Александрович");
Insert into BA values (1412, "Шоу Ирвин");
Insert into BA values (1413, "Шоу Ирвин");
Insert into BA values (1414, "Шоу Ирвин");
Insert into BA values (1415, "Шоу Ирвин");
Insert into BA values (1416, "Шоу Ирвин");
Insert into BA values (1417, "Шушпанов Аркадий Николаевич");
Insert into BA values (1418, "Щепетнов Евгений Владимирович");
Insert into BA values (1419, "Щукин Михаил");
Insert into BA values (1420, "Эд Макдональд");
Insert into BA values (1421, "Эдгар По");
Insert into BA values (1422, "Эдуард Катлас");
Insert into BA values (1423, "Эл Ригби");
Insert into BA values (1424, "Эл Ригби");
Insert into BA values (1425, "Эллендея Проффер");
Insert into BA values (1426, "Эллин Стенли");
Insert into BA values (1427, "Эльчин Сафарли");
Insert into BA values (1428, "Эренбург И.Г.");
Insert into BA values (1429, "Эренбург И.Г.");
Insert into BA values (1430, "Эрика Йохансен");
Insert into BA values (1431, "Эрих Мария Ремарк");
Insert into BA values (1432, "Эрих Мария Ремарк");
Insert into BA values (1433, "Эрл Лори");
Insert into BA values (1433, "Эрл Уэйн");
Insert into BA values (1433, "Эрл Эстер");
Insert into BA values (1434, "Эрнест Хемингуэй");
Insert into BA values (1435, "Эсхил");
Insert into BA values (1436, "Эфрон Георгий Сергеевич");
Insert into BA values (1437, "Эшли Дьюал");
Insert into BA values (1438, "Югов Алексей Кузьмич");
Insert into BA values (1439, "Юзефович Леонид");
Insert into BA values (1440, "Юлия Григорьева");
Insert into BA values (1441, "Юраш Кристина");
Insert into BA values (1442, "Владимир Ценципер");
Insert into BA values (1442, "Юрий Ценципер");
Insert into BA values (1443, "Язвицкий Валерий Иоильевич");
Insert into BA values (1444, "Ян Дошер");
Insert into BA values (1445, "Ян Дошер");
Insert into BA values (1446, "Янковский Дмитрий");
Insert into BA values (1447, "Ярослав Гжендович");
Insert into BA values (1448, "Ясинская Марина");
Insert into BA values (1449, "Ясинский Анджей");
Insert into BA values (1450, "Ясинский Анджей");
Insert into BA values (1451, "Яхина Гузель Шамилевна");